### ISSUE TITLE
Why do I need to follow your dlive account in order to save more stickers?

### ISSUE THREAD

**Issue by Tank-Missile** [zoomerdev/dbased#11]
This must be a recent addition, since I thought half my sticker collection dissappeared after being asked to follow your account.

**Comment by zoomerdev** [comment]
Did the extra stickers come back after you followed or did it delete them permanently? Sorry about the issues

**Comment by Tank-Missile** [comment]
Thankfully the stickers did come back once I followed your account, but why was this artificial limitation put in place all of a sudden? There's nothing in the README or chrome store description that mentions needing to follow your account in order to add more stickers.

**Comment by zoomerdev** [comment]
It's always been that way, however there may be some issues where it doesn't immediately tell you and ends up allowing you to save more for a little while. I understand your confusion but I would encourage you to look at the source code and possibly fork this repo if you would like and publish your own extension. I'm closing this since I don't consider it a bug. Thanks!
